# This is the configuration file for project setup
# config it as required

full_repo_name: 'artm2000/b'
domain: 'https://m8e.ir'
content:
  page_title: MetaReadMe
  introduction: |
    ## Hi, I'm _Alireza_ and 
    # Welcome to MetaReadMe
    ### Let's discover stories together!
author_usernames:
  ARTM2000: Alireza Tanoomandian
