# This is the configuration file for the project setup
# config it as required

full_repo_name: 'artm2000/b'
domain: 'https://m8e.ir'
content:
  page_title: MetaReadMe
  introduction: |
    ## _META-README_
    ### Let's discover stories together!
author_usernames:
  ARTM2000: Alireza Tanoomandian
